### PR TITLE
Update mkdocs.yml (Indonesian, Bahasa Indonesia, ISO 639-1: id)

### PR DESCRIPTION
**Pull request by SergeCroise**

### CODE REVIEW

**Comment by SergeCroise** [comment]
https://github.com/rocky-linux/docs.rockylinux.org/pull/56

**Review by sspencerwire — APPROVED** [review]
@ressonix I'm approving this addition to `mkdocs.yml`... we have a translator for this language, so if you could merge it, that would be great.

**Comment by alemorvan** [comment]
Please let Steven test it on his dev env before merging.
Thx.

**Comment by SergeCroise** [comment]
https://github.com/rocky-linux/documentation/pull/1309

**Comment by SergeCroise** [comment]
Hello @sspencerwire , @wsoyinka 
fyi:
https://github.com/rocky-linux/documentation/blob/main/docs/index.id.md
https://github.com/rocky-linux/documentation/blob/main/docs/release_notes/8-changelog.id.md
https://docs.rockylinux.org/id/

**Comment by SergeCroise** [comment]
> Hello @sspencerwire , @wsoyinka fyi: https://github.com/rocky-linux/documentation/blob/main/docs/index.id.md https://github.com/rocky-linux/documentation/blob/main/docs/release_notes/8-changelog.id.md https://docs.rockylinux.org/id/

see also:
https://docs.rockylinux.org/index.id

**Comment by sspencerwire** [comment]
@ressonix @NebraskaCoder can one of you merge this? I've not loaded this locally, but the configuration *looks* correct and we already have the translation engine piece of this completed and some Indonesian translations merged. Thanks in advance!

**Pull request merged**
